# Generated by Django 5.1.5 on 2025-01-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snip_box_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
